-- Seed: blocks, 144 flats, default super admin
SET NAMES utf8mb4;

INSERT IGNORE INTO blocks (name, sort_order) VALUES
('A', 1),
('B', 2),
('C', 3),
('D', 4);

-- 4 blocks x 9 floors x 4 flats = 144
INSERT IGNORE INTO flats (block_id, flat_no, floor, flat_type, occupancy) VALUES
((SELECT id FROM blocks WHERE name='A'), 'A-101', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-102', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-103', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-104', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-201', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-202', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-203', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-204', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-301', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-302', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-303', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-304', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-401', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-402', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-403', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-404', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-501', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-502', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-503', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-504', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-601', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-602', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-603', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-604', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-701', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-702', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-703', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-704', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-801', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-802', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-803', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-804', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-901', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-902', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-903', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='A'), 'A-904', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-101', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-102', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-103', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-104', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-201', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-202', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-203', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-204', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-301', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-302', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-303', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-304', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-401', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-402', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-403', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-404', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-501', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-502', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-503', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-504', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-601', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-602', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-603', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-604', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-701', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-702', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-703', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-704', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-801', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-802', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-803', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-804', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-901', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-902', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-903', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='B'), 'B-904', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-101', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-102', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-103', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-104', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-201', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-202', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-203', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-204', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-301', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-302', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-303', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-304', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-401', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-402', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-403', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-404', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-501', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-502', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-503', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-504', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-601', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-602', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-603', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-604', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-701', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-702', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-703', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-704', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-801', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-802', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-803', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-804', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-901', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-902', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-903', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='C'), 'C-904', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-101', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-102', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-103', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-104', 1, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-201', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-202', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-203', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-204', 2, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-301', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-302', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-303', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-304', 3, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-401', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-402', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-403', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-404', 4, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-501', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-502', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-503', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-504', 5, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-601', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-602', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-603', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-604', 6, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-701', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-702', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-703', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-704', 7, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-801', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-802', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-803', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-804', 8, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-901', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-902', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-903', 9, '2BHK', 'vacant'),
((SELECT id FROM blocks WHERE name='D'), 'D-904', 9, '2BHK', 'vacant');

-- ------------------------------------------------------------
-- DEFAULT SUPER ADMIN
-- email    : admin@pavanmidway.com
-- username : admin
-- password : Admin@123     <-- CHANGE AFTER FIRST LOGIN
-- ------------------------------------------------------------
INSERT IGNORE INTO users (name, email, username, mobile, password_hash, role, designation, status, must_change_pwd)
VALUES (
  'Society Administrator',
  'admin@pavanmidway.com',
  'admin',
  '9999999999',
  '$2y$10$Bgm370boqcOjxmlb0Toxx.lLF/Htt1XaP5tEdhHBqTkfkNatVcxN6',
  'super_admin',
  'Administrator',
  'active',
  1
);

-- ------------------------------------------------------------
-- DEFAULT SETTINGS
-- ------------------------------------------------------------
INSERT IGNORE INTO settings (key_name, key_value) VALUES
('society_name',        'Pavan Midway Residency'),
('total_flats',         '144'),
('maintenance_amount',  '0'),
('due_day',             '10'),
('late_fee',            '0'),
('currency',            'INR'),
('session_days',        '30'),
('max_login_attempts',  '5'),
('lockout_minutes',     '15');
