-- ============================================================
-- Pavan Midway Residency - Seed data
-- STRUCTURE IS FIXED: 2 blocks x 5 floors x 14 flats = 140
-- Ground floor: GR-A .. GR-N   Upper floors: 1A..1N, 2A..2N, 3A..3N, 4A..4N
-- Flat numbers repeat across blocks; flat_code is the unique ID (A-1A, B-1A)
-- ============================================================
SET NAMES utf8mb4;

-- ---------- BLOCKS ----------
INSERT IGNORE INTO blocks (name, code, total_floors, flats_per_floor, total_flats, is_locked, sort_order) VALUES
('Block A', 'A', 5, 14, 70, 1, 1),
('Block B', 'B', 5, 14, 70, 1, 2);

-- ---------- FLATS (140) ----------
INSERT IGNORE INTO flats (block_id, flat_no, flat_code, floor, floor_label, occupancy, is_locked) VALUES
((SELECT id FROM blocks WHERE code='A'), 'GR-A', 'A-GR-A', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-B', 'A-GR-B', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-C', 'A-GR-C', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-D', 'A-GR-D', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-E', 'A-GR-E', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-F', 'A-GR-F', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-G', 'A-GR-G', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-H', 'A-GR-H', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-I', 'A-GR-I', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-J', 'A-GR-J', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-K', 'A-GR-K', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-L', 'A-GR-L', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-M', 'A-GR-M', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), 'GR-N', 'A-GR-N', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1A', 'A-1A', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1B', 'A-1B', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1C', 'A-1C', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1D', 'A-1D', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1E', 'A-1E', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1F', 'A-1F', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1G', 'A-1G', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1H', 'A-1H', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1I', 'A-1I', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1J', 'A-1J', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1K', 'A-1K', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1L', 'A-1L', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1M', 'A-1M', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '1N', 'A-1N', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2A', 'A-2A', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2B', 'A-2B', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2C', 'A-2C', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2D', 'A-2D', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2E', 'A-2E', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2F', 'A-2F', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2G', 'A-2G', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2H', 'A-2H', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2I', 'A-2I', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2J', 'A-2J', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2K', 'A-2K', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2L', 'A-2L', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2M', 'A-2M', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '2N', 'A-2N', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3A', 'A-3A', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3B', 'A-3B', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3C', 'A-3C', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3D', 'A-3D', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3E', 'A-3E', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3F', 'A-3F', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3G', 'A-3G', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3H', 'A-3H', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3I', 'A-3I', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3J', 'A-3J', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3K', 'A-3K', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3L', 'A-3L', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3M', 'A-3M', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '3N', 'A-3N', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4A', 'A-4A', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4B', 'A-4B', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4C', 'A-4C', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4D', 'A-4D', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4E', 'A-4E', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4F', 'A-4F', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4G', 'A-4G', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4H', 'A-4H', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4I', 'A-4I', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4J', 'A-4J', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4K', 'A-4K', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4L', 'A-4L', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4M', 'A-4M', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='A'), '4N', 'A-4N', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-A', 'B-GR-A', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-B', 'B-GR-B', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-C', 'B-GR-C', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-D', 'B-GR-D', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-E', 'B-GR-E', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-F', 'B-GR-F', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-G', 'B-GR-G', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-H', 'B-GR-H', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-I', 'B-GR-I', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-J', 'B-GR-J', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-K', 'B-GR-K', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-L', 'B-GR-L', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-M', 'B-GR-M', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), 'GR-N', 'B-GR-N', 0, 'Ground', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1A', 'B-1A', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1B', 'B-1B', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1C', 'B-1C', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1D', 'B-1D', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1E', 'B-1E', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1F', 'B-1F', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1G', 'B-1G', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1H', 'B-1H', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1I', 'B-1I', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1J', 'B-1J', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1K', 'B-1K', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1L', 'B-1L', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1M', 'B-1M', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '1N', 'B-1N', 1, '1st Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2A', 'B-2A', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2B', 'B-2B', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2C', 'B-2C', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2D', 'B-2D', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2E', 'B-2E', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2F', 'B-2F', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2G', 'B-2G', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2H', 'B-2H', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2I', 'B-2I', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2J', 'B-2J', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2K', 'B-2K', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2L', 'B-2L', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2M', 'B-2M', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '2N', 'B-2N', 2, '2nd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3A', 'B-3A', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3B', 'B-3B', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3C', 'B-3C', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3D', 'B-3D', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3E', 'B-3E', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3F', 'B-3F', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3G', 'B-3G', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3H', 'B-3H', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3I', 'B-3I', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3J', 'B-3J', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3K', 'B-3K', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3L', 'B-3L', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3M', 'B-3M', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '3N', 'B-3N', 3, '3rd Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4A', 'B-4A', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4B', 'B-4B', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4C', 'B-4C', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4D', 'B-4D', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4E', 'B-4E', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4F', 'B-4F', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4G', 'B-4G', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4H', 'B-4H', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4I', 'B-4I', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4J', 'B-4J', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4K', 'B-4K', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4L', 'B-4L', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4M', 'B-4M', 4, '4th Floor', 'vacant', 1),
((SELECT id FROM blocks WHERE code='B'), '4N', 'B-4N', 4, '4th Floor', 'vacant', 1);

-- ---------- DEFAULT SUPER ADMIN ----------
-- username: admin   password: Admin@123   CHANGE AFTER FIRST LOGIN
INSERT IGNORE INTO users (name, email, username, mobile, password_hash, role, designation, status, must_change_pwd)
VALUES (
  'Society Administrator',
  'admin@pavanmidway.com',
  'admin',
  '9999999999',
  '$2y$10$Bgm370boqcOjxmlb0Toxx.lLF/Htt1XaP5tEdhHBqTkfkNatVcxN6',
  'super_admin',
  'Administrator',
  'active',
  1
);

-- ---------- SETTINGS ----------
INSERT IGNORE INTO settings (key_name, key_value) VALUES
('society_name',        'Pavan Midway Residency'),
('total_blocks',        '2'),
('total_flats',         '140'),
('floors_per_block',    '5'),
('flats_per_floor',     '14'),
('maintenance_amount',  '0'),
('due_day',             '10'),
('late_fee',            '0'),
('currency',            'INR'),
('session_days',        '30'),
('max_login_attempts',  '5'),
('lockout_minutes',     '15');
